# Generated by Django 5.1.6 on 2025-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='project_plans/'),
        ),
    ]
